/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Cloud Catalyst",
  "tagline": "Act as a cloud catalyst",
  "url": "https://ddii.dev",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "ddiiwoong",
  "projectName": "newblog",
  "deploymentBranch": "gh-pages",
  "trailingSlash": true,
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "/home/runner/work/newblog/newblog/sidebars.js",
          "editUrl": "https://github.com/ddiiwoong/newblog/tree/main"
        },
        "gtag": {
          "trackingID": "G-4ZT898XDT2",
          "anonymizeIP": true
        },
        "googleAnalytics": {
          "trackingID": "G-4ZT898XDT2",
          "anonymizeIP": true
        },
        "blog": {
          "routeBasePath": "/",
          "showReadingTime": true,
          "editUrl": "https://github.com/ddiiwoong/newblog/tree/main",
          "blogTitle": "Cloud Catalyst",
          "blogDescription": "My little thought may as a catalyst in other engineer's career",
          "postsPerPage": 5,
          "blogSidebarTitle": "Recent Posts",
          "blogSidebarCount": 5,
          "feedOptions": {
            "type": "all",
            "title": "Act as a catalyst",
            "description": "Act as a cloud catalyst"
          }
        },
        "theme": {
          "customCss": "/home/runner/work/newblog/newblog/src/css/custom.css"
        },
        "sitemap": {}
      }
    ]
  ],
  "plugins": [
    "docusaurus-plugin-google-adsense"
  ],
  "themeConfig": {
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": []
    },
    "metadata": [
      {
        "name": "naver-site-verification",
        "content": "cbcc03783e5594725d3951f4e7f16ede80e69881"
      }
    ],
    "googleAdsense": {
      "dataAdClient": "ca-pub-4362752107119680"
    },
    "algolia": {
      "appId": "UTLA0DRN66",
      "apiKey": "f04922856dcd61505849b49a5bba97d8",
      "indexName": "ddii",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "navbar": {
      "title": "Cloud Catalyst",
      "hideOnScroll": true,
      "logo": {
        "alt": "Cloud Catalyst",
        "src": "img/logo-catalyst.svg"
      },
      "items": [
        {
          "to": "/",
          "label": "Posts",
          "position": "left"
        },
        {
          "type": "dropdown",
          "to": "docs/prometheus/introduction",
          "docId": "introduction",
          "position": "left",
          "label": "Docs",
          "items": [
            {
              "to": "docs/prometheus/introduction",
              "label": "Prometheus"
            }
          ]
        },
        {
          "to": "tags",
          "label": "Tags",
          "position": "right"
        },
        {
          "to": "presentation",
          "label": "Presentation",
          "position": "right"
        },
        {
          "to": "archive",
          "label": "Archive",
          "position": "right"
        },
        {
          "to": "about",
          "label": "About",
          "position": "right"
        },
        {
          "to": "pang4u",
          "label": "Pang4u",
          "position": "right"
        },
        {
          "href": "https://github.com/ddiiwoong/newblog",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ]
    },
    "footer": {
      "style": "light",
      "links": [
        {
          "title": "Blog",
          "items": [
            {
              "label": "Home",
              "to": "/"
            },
            {
              "label": "Archive",
              "to": "archive"
            },
            {
              "label": "Tags",
              "to": "tags"
            }
          ]
        },
        {
          "title": "Sponsors",
          "items": [
            {
              "label": "Pang4U",
              "to": "pang4u"
            },
            {
              "label": "Buy Me a Coffee",
              "href": "https://ko-fi.com/ddiiwoong"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/ddiiwoong"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/ddiiwoong"
            },
            {
              "label": "Facebook",
              "href": "https://www.facebook.com/ddiiwoong"
            },
            {
              "label": "LinkedIn",
              "href": "https://kr.linkedin.com/in/ddiiwoong"
            }
          ]
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage"
    },
    "hideableSidebar": false,
    "autoCollapseSidebarCategories": false,
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
